### ISSUE TITLE
Is there a O3DE version that compiles with cesium-O3DE on Windows 10?

### ISSUE THREAD

**Issue by okerstadt** [CesiumGS/cesium-o3de#58]
Hi. 
I tried to build some combinations of O3DE (21.11,22.10,23.10) and cesium-O3DE (master, 1.1.1, 1.0.0 Binary) with VS2022 on Windows10. None of them works with a newly created project or the cesium-o3de-samples. Is there a combination, that could be built on Windows with VS2022?

Thanks for your help
Okerstadt

**Comment by kring** [comment]
I believe we've only tested O3DE 22.10 and VS2019.

**Comment by okerstadt** [comment]
I don't think that it is a problem with VS2022. Actual master with O3DE 23.10 ends with:
...
-- Using package C:/Prgs/O3DE/3rdParty/packages/OpenMesh-8.1-rev3-windows
CMake Deprecation Warning at C:/Prgs/O3DE/23.10.0/cmake/PAL.cmake:392 (message):
  ly_get_list_relative_pal_filename is being deprecated, change your code to
  use o3de_pal_dir instead.
Call Stack (most recent call first):
  C:/Prgs/O3DE/Gems/cesium-o3de/Code/CMakeLists.txt:8 (ly_get_list_relative_pal_filename)

CMake Error at C:/Prgs/O3DE/Gems/cesium-o3de/Code/CMakeLists.txt:17 (file):
  file failed to open for reading (No such file or directory):

    C:/Prgs/O3DE/Gems/cesium-o3de/Code/../External/Packages/Install/SHA256SUMS

CMake Error at C:/Prgs/O3DE/23.10.0/cmake/3rdPartyPackages.cmake:634 (message):
  ly_associate_package was called without the PACKAGE_HASH argument, this is
  required
Call Stack (most recent call first):
  C:/Prgs/O3DE/Gems/cesium-o3de/Code/CMakeLists.txt:18 (ly_associate_package)

-- Configuring incomplete, errors occurred!

There is no 'Install' folder in External/Packages and there are no other warnings or errors in the log file.

**Comment by okerstadt** [comment]
Actual master with O3DE 22.10 ends with the same error but there is another error before:

Collecting PyYAML==5.4.1
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [62 lines of output]
  C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!
  
          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.
  
          By 2023-Oct-30, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.
  
          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************
  
  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing lib3\PyYAML.egg-info\PKG-INFO
  writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
  writing top-level names to lib3\PyYAML.egg-info\top_level.txt
  Traceback (most recent call last):
    File "C:\Prgs\O3DE\22.10.0\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "C:\Prgs\O3DE\22.10.0\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Prgs\O3DE\22.10.0\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
      super().run_command(command)
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 318, in run
      self.find_sources()
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
      mm.run()
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 548, in run
      self.add_defaults()
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 586, in add_defaults
      sdist.add_defaults(self)
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\command\sdist.py", line 113, in add_defaults
      super().add_defaults()
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "<string>", line 201, in get_source_files
    File "C:\Users\okerstadt\AppData\Local\Temp\pip-build-env-9qvaf92i\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1
